version: "3"
services:

#    pg_jrpc:
#        build:
#            context: ./payment-gateway-jrpc-proxy
#        command: npm start
#        restart: always
#        depends_on:
#            - pg_redis
#        environment:
#            - NODE_ENV=dev
#        networks:
#            - pg-net
#        links:
#            - pg_redis:redis

    nest_mongo:
        image: mongo:latest
        container_name: nest_mongo
        restart: always
        volumes:
            - db-data:/data/db
        networks:
            - nest-net
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor

    nest_mongo-express:
        image: mongo-express
        depends_on:
            - nest_mongo
        links:
            - nest_mongo:mongo
        networks:
            - nest-net
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: toor

#    nest_redis:
#        image: redis
#        restart: always
#        networks:
#            - nest-net
#        ports:
#            - "6379:6379"

networks:
    nest-net:

volumes:
    db-data:
